Revert "[Android] Implement embedding API about loading with overview mode."
This change broke one Android device test:

[FAIL] org.xwalk.core.xwview.test.SetInitialScaleTest#testSetInitialScale2:
junit.framework.AssertionFailedError: expected:<0.25> but was:<1.0>
                                      at org.xwalk.core.xwview.test.SetInitialScaleTest.testSetInitialScale2(SetInitialScaleTest.java:83)
                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                      at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
                                      at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
                                      at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
                                      at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
                                      at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
                                      at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
                                      at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661)

This reverts commit 07e93a089627afa0424c9b4e02aebc84e9514073.

BUG=XWALK-6859