Revert "[Android] Support theme-color on Android Lollipop+(5.0+)"
This reverts commit b1ea577cd3152dd3a522955ff5e9634062427cf1.

Reason: broke Crosswalk 14 beta build from scratch.

runtime/android/core_internal/src/org/xwalk/core/internal/XWalkUIClientInternal.java:105: error: method setStatusBarColor in class ApiCompatibilityUtils cannot be applied to given types;
        ApiCompatibilityUtils.setStatusBarColor(view.getActivity().getWindow(),color);
                             ^
  required: Activity,int
  found: Window,int
  reason: actual argument Window cannot be converted to Activity by method invocation conversion

BUG=XWALK-4305