[Windows] Fix build after the move to Chromium M46.
Basically adapt to https://codereview.chromium.org/1171333003, which
turned net::FormatUrl() into url_formatter:FormatUrl(). Fixes this build
error at least on Windows:

c:\b\b\slave\crosswalk_windows\build\src\xwalk\runtime\browser\runtime_javascript_dialog_manager.cc(56)
: error C2039: 'FormatUrl' : is not a member of 'net'
c:\b\b\slave\crosswalk_windows\build\src\xwalk\runtime\browser\runtime_javascript_dialog_manager.cc(56)
: error C3861: 'FormatUrl': identifier not found