Revert "[Android] Enable the wide viewport quirks mode default."
This commit broke Android tests:

```
[FAIL] org.xwalk.core.internal.xwview.test.ZoomTest#testZoom:
junit.framework.AssertionFailedError: Criteria not met in allotted time.
 at org.chromium.content.browser.test.util.CriteriaHelper.pollForCriteria(CriteriaHelper.java:66)
 at org.xwalk.core.internal.xwview.test.XWalkViewInternalTestBase.poll(XWalkViewInternalTestBase.java:740)
 at org.xwalk.core.internal.xwview.test.XWalkViewInternalTestBase.waitForScaleToBecome(XWalkViewInternalTestBase.java:653)
 at org.xwalk.core.internal.xwview.test.ZoomTest.testZoom(ZoomTest.java:42)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
 at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
 at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
 at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
 at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
 at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
 at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661)
```

```
[FAIL] org.xwalk.core.xwview.test.SetInitialScaleTest#testSetInitialScale2:
junit.framework.AssertionFailedError: expected:<0.25> but was:<1.0>
 at org.xwalk.core.xwview.test.SetInitialScaleTest.testSetInitialScale2(SetInitialScaleTest.java:83)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
 at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
 at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
 at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
 at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
 at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
 at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661)
```

This reverts commit a120a176bbcc98bb2f3b45fa2ae37cbba82c0814.