Revert "[Android] Update shouldInterceptLoadRequest to Android L style"
This reverts commit db7728df0b1324ccc450c2d403376140afc1f8a7.

Reason: broke almost all tests because it uses
android.util.ArrayMap (API Level 19) whereas we need to support API
levels >= 14:

W/System.err( 5990): java.lang.NoClassDefFoundError: android.util.ArrayMap
W/System.err( 5990):    at org.xwalk.core.internal.XWalkContentsIoThreadClient.shouldInterceptRequest(XWalkContentsIoThreadClient.java:53)
W/System.err( 5990):    at dalvik.system.NativeStart.run(Native Method)
F/chromium( 5990): [FATAL:jni_android.cc(249)] Check failed: false. Please include Java exception stack in crash report

BUG=XWALK-3934