[Android] Fix OpenJDK 8 javadoc build after 266c02a0.
Commit 266c02a0 ("[Android] Refine the class description of embedding
API") broke the javadoc build again:

```
../xwalk/runtime/android/core/src/org/xwalk/core/XWalkActivity.java:75: error: malformed HTML
 * properties. </pn.>
               ^
../xwalk/runtime/android/core/src/org/xwalk/core/XWalkActivity.java:75: error: bad use of '>'
 * properties. </pn.>
                    ^
```