[Android] Stop setting |enable_extensions|.
We started setting it in M40 with commit b37ea05 ("Roll 40.0.2214.28"),
likely to work around Chromium change 44b9ce2 ("Cleanup: Prevent usage
of various extension headers when extensions support is not compiled
in") that would otherwise cause the build to fail like this:

In file included from ../../extensions/browser/extension_system.h:13:0,
                 from ../../xwalk/runtime/browser/xwalk_browser_main_parts.cc:24:
../../extensions/common/extension.h:31:2: error: #error "Extensions must be enabled"
 #error "Extensions must be enabled"
  ^
In file included from ../../xwalk/runtime/browser/xwalk_browser_main_parts.cc:24:0:
../../extensions/browser/extension_system.h:16:2: error: #error "Extensions must be enabled"
 #error "Extensions must be enabled"
  ^

The extension_system.h include was added in f463560 ("[Linux] Add NaCl
support"), but it is not actually required to build, so we can just
remove both the include and the variable setting.