Revert "[Android] Fix the potential vulnerability issue."
This reverts commit 4b3000b18cb9f80b5cb41a412b0588758644834a.

The build broke:

```
test/android/core/javatests/src/org/xwalk/core/xwview/test/ClearSslPreferenceTest.java:92: error: cannot find symbol
        assertNull(getCertificateOnUiThread());
                   ^
  symbol:   method getCertificateOnUiThread()
  location: class ClearSslPreferenceTest
test/android/core/javatests/src/org/xwalk/core/xwview/test/ClearSslPreferenceTest.java:96: error: cannot find symbol
        assertNull(getCertificateOnUiThread());
                   ^
  symbol:   method getCertificateOnUiThread()
  location: class ClearSslPreferenceTest
```

BUG=XWALK-6986