Include the right header in runtime_platform_util_aura.cc.
This file, contrary to the other `runtime_platform_util_*.cc` ones, was
including `chrome/browser/platform_util.h` instead of our own
`runtime/browser/runtime_platform_util.h`, leading to build failures in
M49:

In file included from ../../xwalk/runtime/browser/runtime_platform_util_aura.cc:5:
../../chrome/browser/platform_util.h:13:10: fatal error: 'chrome/common/features.h' file not found

BUG=XWALK-6287