Revert "[Android] Decouple XWalkView from the activity"
This reverts commit 6d9c019c4d56880ffce307c49922de110e831432.

It caused some Android tests to fail:

```
[FAIL] org.xwalk.runtime.client.embedded.test.PauseResumeTest#testPauseAndResume:
junit.framework.AssertionFailedError: The second title should be equal to the first title.
    at org.xwalk.test.util.RuntimeClientApiTestBase.compareTitle(RuntimeClientApiTestBase.java:68)
    at org.xwalk.test.util.RuntimeClientApiTestBase.testPauseAndResume(RuntimeClientApiTestBase.java:348)
    at org.xwalk.runtime.client.embedded.test.PauseResumeTest.testPauseAndResume(PauseResumeTest.java:25)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
    at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
    at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
    at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661)
```

```
[FAIL] org.xwalk.runtime.client.test.PauseResumeTest#testPauseAndResume:
junit.framework.AssertionFailedError: The second title should be equal to the first title.
    at org.xwalk.test.util.RuntimeClientApiTestBase.compareTitle(RuntimeClientApiTestBase.java:68)
    at org.xwalk.test.util.RuntimeClientApiTestBase.testPauseAndResume(RuntimeClientApiTestBase.java:348)
    at org.xwalk.runtime.client.test.PauseResumeTest.testPauseAndResume(PauseResumeTest.java:25)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
    at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
    at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
    at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661)
```