[Android] Fix javadoc build after 8705e628.
Commit 8705e6288cbdf8a93da42a181749e6c5859b8064 ("[Android] Support
XWalkRuntimeLib.apk download for multiple architectures") broke the
build:

../xwalk/runtime/android/core/src/org/xwalk/core/XWalkUpdater.java:53: error: end tag missing: </code>
 * <p>To download the Crosswalk runtime APK for the specified CPU architecture, <code>xwalk_apk_url<code>
                                                                                                   ^
../xwalk/runtime/android/core/src/org/xwalk/core/XWalkUpdater.java:53: error: end tag missing: </code>
 * <p>To download the Crosswalk runtime APK for the specified CPU architecture, <code>xwalk_apk_url<code>
                                                                                ^