[Android] Fix javadoc build with JDK 1.8.
Fix build errors caused by commits 5505ef4 ("[Android] Refactor download
mode") and 1c6ecad ("[Android] Implement the method to set compositing
surface type for single XWalkView"):

```
../xwalk/runtime/android/core/src/org/xwalk/core/XWalkActivity.java:60: error: header used out of sequence: <H5>
 * <h5>Shared Mode</h5>
   ^
../xwalk/runtime/android/core/src/org/xwalk/core/XWalkUpdater.java:172: error: header used out of sequence: <H5>
 * <h5>Shared Mode</h5>
   ^
../out/Release/gen/xwalk_core_reflection_layer/wrapper/org/xwalk/core/XWalkView.java:96: error: text not allowed in <ol> element
 *   </li></ul></li>
                    ^
```

(cherry picked from commit f6943eea83a478a167a08053210ac3ffcc41e0c8)