Change target name from api to xwalk_jsapi.
The api target is taken common/extensions/api/api.gyp. This results in the following
warning in the android build.

ninja: warning: multiple rules generate libapi.a. builds involving this target will not be correct; continuing anyway

The build itself later errors with
gen/chrome/common/extensions/api/generated_schemas.cc:11:6: error: 'GeneratedSchemas' has not been declared
(because it built the target in api.gyp).