Eliminate comparison of integers of different signs, unused const variables in xwalk/application.
With more strict compile options like "-Wunused-const-variable" and
"-Wsign-compare", errors are found during building:
../../xwalk/application/common/application_file_util.cc:173:21:
error: comparison of integers of different signs: 'int' and
'unsigned long' [-Werror,-Wsign-compare]
../../xwalk/application/common/application_file_util.cc:45:12:
error: unused variable 'kContentKey' [-Werror,-Wunused-const-variable]
../../xwalk/application/common/package/xpk_package.cc:18:15:
error: unused variable 'kSignatureAlgorithm' [-Werror,-Wunused-const-variable]
../../xwalk/application/extension/application_widget_storage.cc:47:12:
error: unused variable 'kSelectTableLength' [-Werror,-Wunused-const-variable]

Remove Un-used const variables, change int into size_t type.

BUG=XWALK-7201