[Android]Fix Android build failure from scratch after b6623da. This happens on the Android debug builds because of lack of the dependency on ui/compositor when building the source files splash_screen.h|.cc. Here is the error message:     obj/xwalk/libxwalk_runtime.a(obj/xwalk/runtime/browser/ui/xwalk_runtime.splash_screen.o): in function vtable for xwalk::SplashScreen:splash_screen.cc(.data.rel.ro._ZTVN5xwalk12SplashScreenE+0x134): error: undefined reference to 'ui::ImplicitAnimationObserver::OnAttachedToSequence(ui::LayerAnimationSequence*)'
Since the splash_screen.h|.cc are tizen-specific, this fix is to rename the files by adding suffix "_tizen" so that they can excluded from Android builds. The class name is also modified to keep consistency, e.g change class SplashScreen to class SplashScreenTizen.