Revert "[Android] Implement the feature about custom url scheme."
This commit broke Android tests:

```
[FAIL] org.xwalk.core.internal.xwview.test.HandleActionUriTest#testSmsUri:
junit.framework.ComparisonFailure: expected:<vnd.android-dir/mms-sms> but was:<null>
 at org.xwalk.core.internal.xwview.test.HandleActionUriTest.testSmsUri(HandleActionUriTest.java:92)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
 at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
 at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
 at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
 at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
 at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
 at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1661)
```

This reverts commit f7e19b9865144c94772c158ca20e708a35a1bc5b.